
version: "3"

services:
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
      - "2003:2003"
    environment:
      INFLUXDB_ADMIN_ENABLED: "true"
    networks:
      - my-net
    volumes:
      - "./influxdb.conf:/etc/influxdb/influxdb.conf:ro"
      - "/home/perfana/influxdb-data:/var/lib/influxdb"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

  grafana:
    image: "grafana/grafana"
    depends_on:
      - influxdb
    environment:
      GF_SECURITY_ADMIN_USER: foobar
      GF_SECURITY_ADMIN_PASSWORD: foobar
      GF_SERVER_ROOT_URL: "http://49.27.22.156:3000"
    ports:
      - "3000:3000"
    networks:
      - my-net
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

  perfana:
    image: "perfana/perfana:0.24.1"
    depends_on:
      - grafana
      - influxdb
    environment:
      ROOT_URL: "http://49.27.22.156:4000"
      MONGO_URL: "mongodb://mongo:27017"
      METEOR_SETTINGS: '{"isDemo": true,"autoCreateApplications": true,"snapshotExpires": "7776000","perfanaHost":"http://49.27.22.156:3000","influxDbHost": "influxdb","public": {"perfanaHost":"http://49.27.22.156:4000","OIDCButtonText": "AH LDAP Login"}}'
    ports:
      - "4000:3000"
    networks:
      - my-net
    restart: always
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"


  mongo:
    image: mongo:3.0
    ports:
    - "27017:27017"
    networks:
    - my-net
    command: --smallfiles
    volumes:
    - "/home/perfana/mongo-data:/data/db"
    - "/etc/timezone:/etc/timezone:ro"
    - "/etc/localtime:/etc/localtime:ro"
 
networks:
    my-net:
      driver: bridge
